/**
 * Generate a fresh VAPID keypair for Web Push.
 *
 * Run via:
 *   pnpm hermes-van:vapid
 *
 * Prints the keys + suggested subject so you can paste them straight
 * into .env. Does not write to .env automatically — that's a destructive
 * op that should be conscious. The public key is safe to expose; the
 * private key MUST stay server-side.
 */
import webpush from "web-push";

const keys = webpush.generateVAPIDKeys();

const lines = [
  "# Generated by scripts/vapid.ts — paste into web/.env",
  `HERMES_VAN_VAPID_PUBLIC=${keys.publicKey}`,
  `HERMES_VAN_VAPID_PRIVATE=${keys.privateKey}`,
  `HERMES_VAN_VAPID_SUBJECT=mailto:noreply@hermes-van.local`,
];

// eslint-disable-next-line no-console
console.log(lines.join("\n"));
