allowBuilds:
  better-sqlite3-multiple-ciphers: set this to true or false
  esbuild: set this to true or false
onlyBuiltDependencies:
  - "@node-rs/argon2"
  - better-sqlite3-multiple-ciphers
  - esbuild
